on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: test
    steps:
      - uses: actions/checkout@v4
      - name: Hello world action step
        uses: ./
        with:
          jdk_dist: '17-graal'
