name: 'test'

on:
  push:
    branches:
      - test

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./
      with:
        jdk_dist: '17.0.10-graal'
        registry_username: dima
        registry_password: ${{ secrets.REGISTRY_PASSWORD }}
        registry_hostname: registry.reachhold.com
